--RELATÓRIO FAROL BAINCONDRES GIVALDO


WITH TEMPO AS (
	SELECT
		PRO.MARCA,
		EST.CODPROD,
		PRO.DESCRPROD,
		EST.ESTMIN,
		EST.ESTOQUE,
		DIS.DESCSTATUS,
		MAX(EST.ESTMIN - EST.ESTOQUE) AS DIFERENCA,
		ROUND(AVG(IT.VLRTOT),2) AS MED_VEND,
	    (AVG(IT.VLRTOT)/30) * (45 - EST.ESTOQUE) AS SUG45,
		SANKHYA.OBTEMCUSTO(EST.CODPROD, 'N', '', 'N', '', 'N', '', GETDATE(), 0) AS CUSTO_REPOSICAO
	FROM TGFPRO PRO
	INNER JOIN TGFITE IT ON IT.CODPROD = PRO.CODPROD
    INNER JOIN TGFEST EST ON EST.CODPROD= IT.CODPROD 
    	AND EST.CODEMP = IT.CODEMP 
    	AND EST.CODLOCAL = IT.CODLOCALORIG 
    	AND EST.CONTROLE = IT.CONTROLE
	INNER JOIN TGFCAB CB ON CB.NUNOTA =IT.NUNOTA
	LEFT JOIN AD_STATUS DIS ON DIS.CODIGO = PRO.AD_CODIGO
	INNER JOIN TGFITE ITE ON ITE.NUNOTA = CB.NUNOTA
	WHERE PRO.MARCA IN ('BIANCOGRES', 'INCESA')
	--AND CB.CODTIPOPER IN (1154, 1108, 1101)
	--AND VEN.TIPVEND = 'V'
	AND EST.CODEMP IN (4,9)
	AND CB.DTFATUR BETWEEN DATEADD(MONTH, -6, GETDATE()) AND GETDATE()
	AND DIS.DESCSTATUS IS NOT NULL
	AND ITE.QTDNEG >= 300
	GROUP BY
		    EST.ESTOQUE,
			IT.VLRTOT,
			EST.ESTMIN,
			PRO.MARCA,
			PRO.DESCRPROD,
			DIS.DESCSTATUS,
			ITE.QTDNEG, 
			EST.CODPROD
	) 
	
	
--VAI APARECER NA TELA FINAL
SELECT TOP 50
	MARCA,
	CODPROD,
	DESCRPROD,
	ESTMIN,
	ESTOQUE AS EST_ATUAL,
	DIFERENCA,
	MED_VEND,
	ROUND((ESTOQUE / MED_VEND),2) * 30 AS DDE,
	ROUND(CUSTO_REPOSICAO,2)AS CUST_REP,
	ROUND(SUG45,2) AS SUG_45D,
	ROUND((CUSTO_REPOSICAO * SUG45 ),2) AS SUGCOMP,
	DIFERENCA AS SUG30,
	ROUND((DIFERENCA * CUSTO_REPOSICAO),2) AS VLRCOMP 
FROM TEMPO ;
 

